INSERT INTO pais (id, nome) VALUES (1, 'Afeganistão');
INSERT INTO pais (id, nome) VALUES (2, 'África do Sul');
INSERT INTO pais (id, nome) VALUES (3, 'Akrotiri');
INSERT INTO pais (id, nome) VALUES (4, 'Albânia');
INSERT INTO pais (id, nome) VALUES (5, 'Alemanha');
INSERT INTO pais (id, nome) VALUES (6, 'Andorra');
INSERT INTO pais (id, nome) VALUES (7, 'Angola');
INSERT INTO pais (id, nome) VALUES (8, 'Anguila');
INSERT INTO pais (id, nome) VALUES (9, 'Antárctida');
INSERT INTO pais (id, nome) VALUES (10, 'Antígua e Barbuda');
INSERT INTO pais (id, nome) VALUES (11, 'Arábia Saudita');
INSERT INTO pais (id, nome) VALUES (12, 'Arctic Ocean');
INSERT INTO pais (id, nome) VALUES (13, 'Argélia');
INSERT INTO pais (id, nome) VALUES (14, 'Argentina');
INSERT INTO pais (id, nome) VALUES (15, 'Arménia');
INSERT INTO pais (id, nome) VALUES (16, 'Aruba');
INSERT INTO pais (id, nome) VALUES (17, 'Ashmore and Cartier Islands');
INSERT INTO pais (id, nome) VALUES (18, 'Atlantic Ocean');
INSERT INTO pais (id, nome) VALUES (19, 'Austrália');
INSERT INTO pais (id, nome) VALUES (20, 'Áustria');
INSERT INTO pais (id, nome) VALUES (21, 'Azerbaijão');
INSERT INTO pais (id, nome) VALUES (22, 'Baamas');
INSERT INTO pais (id, nome) VALUES (23, 'Bangladeche');
INSERT INTO pais (id, nome) VALUES (24, 'Barbados');
INSERT INTO pais (id, nome) VALUES (25, 'Barém');
INSERT INTO pais (id, nome) VALUES (26, 'Bélgica');
INSERT INTO pais (id, nome) VALUES (27, 'Belize');
INSERT INTO pais (id, nome) VALUES (28, 'Benim');
INSERT INTO pais (id, nome) VALUES (29, 'Bermudas');
INSERT INTO pais (id, nome) VALUES (30, 'Bielorrússia');
INSERT INTO pais (id, nome) VALUES (31, 'Birmânia');
INSERT INTO pais (id, nome) VALUES (32, 'Bolívia');
INSERT INTO pais (id, nome) VALUES (33, 'Bósnia e Herzegovina');
INSERT INTO pais (id, nome) VALUES (34, 'Botsuana');
INSERT INTO pais (id, nome) VALUES (35, 'Brasil');
INSERT INTO pais (id, nome) VALUES (36, 'Brunei');
INSERT INTO pais (id, nome) VALUES (37, 'Bulgária');
INSERT INTO pais (id, nome) VALUES (38, 'Burquina Faso');
INSERT INTO pais (id, nome) VALUES (39, 'Burúndi');
INSERT INTO pais (id, nome) VALUES (40, 'Butão');
INSERT INTO pais (id, nome) VALUES (41, 'Cabo Verde');
INSERT INTO pais (id, nome) VALUES (42, 'Camarões');
INSERT INTO pais (id, nome) VALUES (43, 'Camboja');
INSERT INTO pais (id, nome) VALUES (44, 'Canadá');
INSERT INTO pais (id, nome) VALUES (45, 'Catar');
INSERT INTO pais (id, nome) VALUES (46, 'Cazaquistão');
INSERT INTO pais (id, nome) VALUES (47, 'Chade');
INSERT INTO pais (id, nome) VALUES (48, 'Chile');
INSERT INTO pais (id, nome) VALUES (49, 'China');
INSERT INTO pais (id, nome) VALUES (50, 'Chipre');
INSERT INTO pais (id, nome) VALUES (51, 'Clipperton Island');
INSERT INTO pais (id, nome) VALUES (52, 'Colômbia');
INSERT INTO pais (id, nome) VALUES (53, 'Comores');
INSERT INTO pais (id, nome) VALUES (54, 'Congo-Brazzaville');
INSERT INTO pais (id, nome) VALUES (55, 'Congo-Kinshasa');
INSERT INTO pais (id, nome) VALUES (56, 'Coral Sea Islands');
INSERT INTO pais (id, nome) VALUES (57, 'Coreia do Norte');
INSERT INTO pais (id, nome) VALUES (58, 'Coreia do Sul');
INSERT INTO pais (id, nome) VALUES (59, 'Costa do Marfim');
INSERT INTO pais (id, nome) VALUES (60, 'Costa Rica');
INSERT INTO pais (id, nome) VALUES (61, 'Croácia');
INSERT INTO pais (id, nome) VALUES (62, 'Cuba');
INSERT INTO pais (id, nome) VALUES (63, 'Curacao');
INSERT INTO pais (id, nome) VALUES (64, 'Dhekelia');
INSERT INTO pais (id, nome) VALUES (65, 'Dinamarca');
INSERT INTO pais (id, nome) VALUES (66, 'Domínica');
INSERT INTO pais (id, nome) VALUES (67, 'Egipto');
INSERT INTO pais (id, nome) VALUES (68, 'Emiratos Árabes Unidos');
INSERT INTO pais (id, nome) VALUES (69, 'Equador');
INSERT INTO pais (id, nome) VALUES (70, 'Eritreia');
INSERT INTO pais (id, nome) VALUES (71, 'Eslováquia');
INSERT INTO pais (id, nome) VALUES (72, 'Eslovénia');
INSERT INTO pais (id, nome) VALUES (73, 'Espanha');
INSERT INTO pais (id, nome) VALUES (74, 'Estados Unidos');
INSERT INTO pais (id, nome) VALUES (75, 'Estónia');
INSERT INTO pais (id, nome) VALUES (76, 'Etiópia');
INSERT INTO pais (id, nome) VALUES (77, 'Faroé');
INSERT INTO pais (id, nome) VALUES (78, 'Fiji');
INSERT INTO pais (id, nome) VALUES (79, 'Filipinas');
INSERT INTO pais (id, nome) VALUES (80, 'Finlândia');
INSERT INTO pais (id, nome) VALUES (81, 'França');
INSERT INTO pais (id, nome) VALUES (82, 'Gabão');
INSERT INTO pais (id, nome) VALUES (83, 'Gâmbia');
INSERT INTO pais (id, nome) VALUES (84, 'Gana');
INSERT INTO pais (id, nome) VALUES (85, 'Gaza Strip');
INSERT INTO pais (id, nome) VALUES (86, 'Geórgia');
INSERT INTO pais (id, nome) VALUES (87, 'Geórgia do Sul e Sandwich do Sul');
INSERT INTO pais (id, nome) VALUES (88, 'Gibraltar');
INSERT INTO pais (id, nome) VALUES (89, 'Granada');
INSERT INTO pais (id, nome) VALUES (90, 'Grécia');
INSERT INTO pais (id, nome) VALUES (91, 'Gronelândia');
INSERT INTO pais (id, nome) VALUES (92, 'Guame');
INSERT INTO pais (id, nome) VALUES (93, 'Guatemala');
INSERT INTO pais (id, nome) VALUES (94, 'Guernsey');
INSERT INTO pais (id, nome) VALUES (95, 'Guiana');
INSERT INTO pais (id, nome) VALUES (96, 'Guiné');
INSERT INTO pais (id, nome) VALUES (97, 'Guiné Equatorial');
INSERT INTO pais (id, nome) VALUES (98, 'Guiné-Bissau');
INSERT INTO pais (id, nome) VALUES (99, 'Haiti');
INSERT INTO pais (id, nome) VALUES (100, 'Honduras');
INSERT INTO pais (id, nome) VALUES (101, 'Hong Kong');
INSERT INTO pais (id, nome) VALUES (102, 'Hungria');
INSERT INTO pais (id, nome) VALUES (103, 'Iémen');
INSERT INTO pais (id, nome) VALUES (104, 'Ilha Bouvet');
INSERT INTO pais (id, nome) VALUES (105, 'Ilha do Natal');
INSERT INTO pais (id, nome) VALUES (106, 'Ilha Norfolk');
INSERT INTO pais (id, nome) VALUES (107, 'Ilhas Caimão');
INSERT INTO pais (id, nome) VALUES (108, 'Ilhas Cook');
INSERT INTO pais (id, nome) VALUES (109, 'Ilhas dos Cocos');
INSERT INTO pais (id, nome) VALUES (110, 'Ilhas Falkland');
INSERT INTO pais (id, nome) VALUES (111, 'Ilhas Heard e McDonald');
INSERT INTO pais (id, nome) VALUES (112, 'Ilhas Marshall');
INSERT INTO pais (id, nome) VALUES (113, 'Ilhas Salomão');
INSERT INTO pais (id, nome) VALUES (114, 'Ilhas Turcas e Caicos');
INSERT INTO pais (id, nome) VALUES (115, 'Ilhas Virgens Americanas');
INSERT INTO pais (id, nome) VALUES (116, 'Ilhas Virgens Britânicas');
INSERT INTO pais (id, nome) VALUES (117, 'Índia');
INSERT INTO pais (id, nome) VALUES (118, 'Indian Ocean');
INSERT INTO pais (id, nome) VALUES (119, 'Indonésia');
INSERT INTO pais (id, nome) VALUES (120, 'Irão');
INSERT INTO pais (id, nome) VALUES (121, 'Iraque');
INSERT INTO pais (id, nome) VALUES (122, 'Irlanda');
INSERT INTO pais (id, nome) VALUES (123, 'Islândia');
INSERT INTO pais (id, nome) VALUES (124, 'Israel');
INSERT INTO pais (id, nome) VALUES (125, 'Itália');
INSERT INTO pais (id, nome) VALUES (126, 'Jamaica');
INSERT INTO pais (id, nome) VALUES (127, 'Jan Mayen');
INSERT INTO pais (id, nome) VALUES (128, 'Japão');
INSERT INTO pais (id, nome) VALUES (129, 'Jersey');
INSERT INTO pais (id, nome) VALUES (130, 'Jibuti');
INSERT INTO pais (id, nome) VALUES (131, 'Jordânia');
INSERT INTO pais (id, nome) VALUES (132, 'Kosovo');
INSERT INTO pais (id, nome) VALUES (133, 'Kuwait');
INSERT INTO pais (id, nome) VALUES (134, 'Laos');
INSERT INTO pais (id, nome) VALUES (135, 'Lesoto');
INSERT INTO pais (id, nome) VALUES (136, 'Letónia');
INSERT INTO pais (id, nome) VALUES (137, 'Líbano');
INSERT INTO pais (id, nome) VALUES (138, 'Libéria');
INSERT INTO pais (id, nome) VALUES (139, 'Líbia');
INSERT INTO pais (id, nome) VALUES (140, 'Listenstaine');
INSERT INTO pais (id, nome) VALUES (141, 'Lituânia');
INSERT INTO pais (id, nome) VALUES (142, 'Luxemburgo');
INSERT INTO pais (id, nome) VALUES (143, 'Macau');
INSERT INTO pais (id, nome) VALUES (144, 'Macedónia');
INSERT INTO pais (id, nome) VALUES (145, 'Madagáscar');
INSERT INTO pais (id, nome) VALUES (146, 'Malásia');
INSERT INTO pais (id, nome) VALUES (147, 'Malávi');
INSERT INTO pais (id, nome) VALUES (148, 'Maldivas');
INSERT INTO pais (id, nome) VALUES (149, 'Mali');
INSERT INTO pais (id, nome) VALUES (150, 'Malta');
INSERT INTO pais (id, nome) VALUES (151, 'Man, Isle of');
INSERT INTO pais (id, nome) VALUES (152, 'Marianas do Norte');
INSERT INTO pais (id, nome) VALUES (153, 'Marrocos');
INSERT INTO pais (id, nome) VALUES (154, 'Maurícia');
INSERT INTO pais (id, nome) VALUES (155, 'Mauritânia');
INSERT INTO pais (id, nome) VALUES (156, 'México');
INSERT INTO pais (id, nome) VALUES (157, 'Micronésia');
INSERT INTO pais (id, nome) VALUES (158, 'Moçambique');
INSERT INTO pais (id, nome) VALUES (159, 'Moldávia');
INSERT INTO pais (id, nome) VALUES (160, 'Mónaco');
INSERT INTO pais (id, nome) VALUES (161, 'Mongólia');
INSERT INTO pais (id, nome) VALUES (162, 'Monserrate');
INSERT INTO pais (id, nome) VALUES (163, 'Montenegro');
INSERT INTO pais (id, nome) VALUES (164, 'Mundo');
INSERT INTO pais (id, nome) VALUES (165, 'Namíbia');
INSERT INTO pais (id, nome) VALUES (166, 'Nauru');
INSERT INTO pais (id, nome) VALUES (167, 'Navassa Island');
INSERT INTO pais (id, nome) VALUES (168, 'Nepal');
INSERT INTO pais (id, nome) VALUES (169, 'Nicarágua');
INSERT INTO pais (id, nome) VALUES (170, 'Níger');
INSERT INTO pais (id, nome) VALUES (171, 'Nigéria');
INSERT INTO pais (id, nome) VALUES (172, 'Niue');
INSERT INTO pais (id, nome) VALUES (173, 'Noruega');
INSERT INTO pais (id, nome) VALUES (174, 'Nova Caledónia');
INSERT INTO pais (id, nome) VALUES (175, 'Nova Zelândia');
INSERT INTO pais (id, nome) VALUES (176, 'Omã');
INSERT INTO pais (id, nome) VALUES (177, 'Pacific Ocean');
INSERT INTO pais (id, nome) VALUES (178, 'Países Baixos');
INSERT INTO pais (id, nome) VALUES (179, 'Palau');
INSERT INTO pais (id, nome) VALUES (180, 'Panamá');
INSERT INTO pais (id, nome) VALUES (181, 'Papua-Nova Guiné');
INSERT INTO pais (id, nome) VALUES (182, 'Paquistão');
INSERT INTO pais (id, nome) VALUES (183, 'Paracel Islands');
INSERT INTO pais (id, nome) VALUES (184, 'Paraguai');
INSERT INTO pais (id, nome) VALUES (185, 'Peru');
INSERT INTO pais (id, nome) VALUES (186, 'Pitcairn');
INSERT INTO pais (id, nome) VALUES (187, 'Polinésia Francesa');
INSERT INTO pais (id, nome) VALUES (188, 'Polónia');
INSERT INTO pais (id, nome) VALUES (189, 'Porto Rico');
INSERT INTO pais (id, nome) VALUES (190, 'Portugal');
INSERT INTO pais (id, nome) VALUES (191, 'Quénia');
INSERT INTO pais (id, nome) VALUES (192, 'Quirguizistão');
INSERT INTO pais (id, nome) VALUES (193, 'Quiribáti');
INSERT INTO pais (id, nome) VALUES (194, 'Reino Unido');
INSERT INTO pais (id, nome) VALUES (195, 'República Centro-Africana');
INSERT INTO pais (id, nome) VALUES (196, 'República Dominicana');
INSERT INTO pais (id, nome) VALUES (197, 'Roménia');
INSERT INTO pais (id, nome) VALUES (198, 'Ruanda');
INSERT INTO pais (id, nome) VALUES (199, 'Rússia');
INSERT INTO pais (id, nome) VALUES (200, 'Salvador');
INSERT INTO pais (id, nome) VALUES (201, 'Samoa');
INSERT INTO pais (id, nome) VALUES (202, 'Samoa Americana');
INSERT INTO pais (id, nome) VALUES (203, 'Santa Helena');
INSERT INTO pais (id, nome) VALUES (204, 'Santa Lúcia');
INSERT INTO pais (id, nome) VALUES (205, 'São Bartolomeu');
INSERT INTO pais (id, nome) VALUES (206, 'São Cristóvão e Neves');
INSERT INTO pais (id, nome) VALUES (207, 'São Marinho');
INSERT INTO pais (id, nome) VALUES (208, 'São Martinho');
INSERT INTO pais (id, nome) VALUES (209, 'São Pedro e Miquelon');
INSERT INTO pais (id, nome) VALUES (210, 'São Tomé e Príncipe');
INSERT INTO pais (id, nome) VALUES (211, 'São Vicente e Granadinas');
INSERT INTO pais (id, nome) VALUES (212, 'Sara Ocidental');
INSERT INTO pais (id, nome) VALUES (213, 'Seicheles');
INSERT INTO pais (id, nome) VALUES (214, 'Senegal');
INSERT INTO pais (id, nome) VALUES (215, 'Serra Leoa');
INSERT INTO pais (id, nome) VALUES (216, 'Sérvia');
INSERT INTO pais (id, nome) VALUES (217, 'Singapura');
INSERT INTO pais (id, nome) VALUES (218, 'Sint Maarten');
INSERT INTO pais (id, nome) VALUES (219, 'Síria');
INSERT INTO pais (id, nome) VALUES (220, 'Somália');
INSERT INTO pais (id, nome) VALUES (221, 'Southern Ocean');
INSERT INTO pais (id, nome) VALUES (222, 'Spratly Islands');
INSERT INTO pais (id, nome) VALUES (223, 'Sri Lanca');
INSERT INTO pais (id, nome) VALUES (224, 'Suazilândia');
INSERT INTO pais (id, nome) VALUES (225, 'Sudão');
INSERT INTO pais (id, nome) VALUES (226, 'Sudão do Sul');
INSERT INTO pais (id, nome) VALUES (227, 'Suécia');
INSERT INTO pais (id, nome) VALUES (228, 'Suíça');
INSERT INTO pais (id, nome) VALUES (229, 'Suriname');
INSERT INTO pais (id, nome) VALUES (230, 'Svalbard e Jan Mayen');
INSERT INTO pais (id, nome) VALUES (231, 'Tailândia');
INSERT INTO pais (id, nome) VALUES (232, 'Taiwan');
INSERT INTO pais (id, nome) VALUES (233, 'Tajiquistão');
INSERT INTO pais (id, nome) VALUES (234, 'Tanzânia');
INSERT INTO pais (id, nome) VALUES (235, 'Território Britânico do Oceano Índico');
INSERT INTO pais (id, nome) VALUES (236, 'Territórios Austrais Franceses');
INSERT INTO pais (id, nome) VALUES (237, 'Timor Leste');
INSERT INTO pais (id, nome) VALUES (238, 'Togo');
INSERT INTO pais (id, nome) VALUES (239, 'Tokelau');
INSERT INTO pais (id, nome) VALUES (240, 'Tonga');
INSERT INTO pais (id, nome) VALUES (241, 'Trindade e Tobago');
INSERT INTO pais (id, nome) VALUES (242, 'Tunísia');
INSERT INTO pais (id, nome) VALUES (243, 'Turquemenistão');
INSERT INTO pais (id, nome) VALUES (244, 'Turquia');
INSERT INTO pais (id, nome) VALUES (245, 'Tuvalu');
INSERT INTO pais (id, nome) VALUES (246, 'Ucrânia');
INSERT INTO pais (id, nome) VALUES (247, 'Uganda');
INSERT INTO pais (id, nome) VALUES (248, 'União Europeia');
INSERT INTO pais (id, nome) VALUES (249, 'Uruguai');
INSERT INTO pais (id, nome) VALUES (250, 'Usbequistão');
INSERT INTO pais (id, nome) VALUES (251, 'Vanuatu');
INSERT INTO pais (id, nome) VALUES (252, 'Vaticano');
INSERT INTO pais (id, nome) VALUES (253, 'Venezuela');
INSERT INTO pais (id, nome) VALUES (254, 'Vietname');
INSERT INTO pais (id, nome) VALUES (255, 'Wake Island');
INSERT INTO pais (id, nome) VALUES (256, 'Wallis e Futuna');
INSERT INTO pais (id, nome) VALUES (257, 'West Bank');
INSERT INTO pais (id, nome) VALUES (258, 'Zâmbia');
INSERT INTO pais (id, nome) VALUES (259, 'Zimbabué');

INSERT INTO torneio (id, nome) VALUES (1, 'Mundial de seleções');
INSERT INTO torneio (id, nome) VALUES (2, 'Mundial de clubes');
INSERT INTO torneio (id, nome) VALUES (3, 'Champions Leaugue');
INSERT INTO torneio (id, nome) VALUES (4, 'Copa América');
INSERT INTO torneio (id, nome) VALUES (5, 'Eurocopa');
INSERT INTO torneio (id, nome) VALUES (6, 'Libertadores');
INSERT INTO torneio (id, nome) VALUES (7, 'Sulamericana');
INSERT INTO torneio (id, nome) VALUES (8, 'Copa Confederações');

INSERT INTO grupo (id, nome) VALUES (1, 'A');
INSERT INTO grupo (id, nome) VALUES (2, 'B');
INSERT INTO grupo (id, nome) VALUES (3, 'C');
INSERT INTO grupo (id, nome) VALUES (4, 'D');
INSERT INTO grupo (id, nome) VALUES (5, 'E');
INSERT INTO grupo (id, nome) VALUES (6, 'F');
INSERT INTO grupo (id, nome) VALUES (7, 'G');
INSERT INTO grupo (id, nome) VALUES (8, 'H');

INSERT INTO fase (id, nome) VALUES (1, 'Grupos');
INSERT INTO fase (id, nome) VALUES (2, 'Oitavas');
INSERT INTO fase (id, nome) VALUES (3, 'Quartas');
INSERT INTO fase (id, nome) VALUES (4, 'Semifinal');
INSERT INTO fase (id, nome) VALUES (5, 'Final');
INSERT INTO fase (id, nome) VALUES (6, 'Terceiro Lugar');

INSERT INTO equipe (id, nome, id_pais) VALUES (1, 'Seleção Brasil', 35);
INSERT INTO equipe (id, nome, id_pais) VALUES (2, 'Seleção Espanha', 73);

INSERT INTO jogo (id_equipe_um, id_equipe_dois, placar_equipe_um, placar_equipe_dois, id_fase, id_grupo, id_torneio) VALUES(1,2,3,0,5,null,8);








