INSERT INTO mhj06.pais (nome) VALUES ('Afeganistão');
INSERT INTO mhj06.pais (nome) VALUES ('África do Sul');
INSERT INTO mhj06.pais (nome) VALUES ('Akrotiri');
INSERT INTO mhj06.pais (nome) VALUES ('Albânia');
INSERT INTO mhj06.pais (nome) VALUES ('Alemanha');
INSERT INTO mhj06.pais (nome) VALUES ('Andorra');
INSERT INTO mhj06.pais (nome) VALUES ('Angola');
INSERT INTO mhj06.pais (nome) VALUES ('Anguila');
INSERT INTO mhj06.pais (nome) VALUES ('Antárctida');
INSERT INTO mhj06.pais (nome) VALUES ('Antígua e Barbuda');
INSERT INTO mhj06.pais (nome) VALUES ('Arábia Saudita');
INSERT INTO mhj06.pais (nome) VALUES ('Arctic Ocean');
INSERT INTO mhj06.pais (nome) VALUES ('Argélia');
INSERT INTO mhj06.pais (nome) VALUES ('Argentina');
INSERT INTO mhj06.pais (nome) VALUES ('Arménia');
INSERT INTO mhj06.pais (nome) VALUES ('Aruba');
INSERT INTO mhj06.pais (nome) VALUES ('Ashmore and Cartier Islands');
INSERT INTO mhj06.pais (nome) VALUES ('Atlantic Ocean');
INSERT INTO mhj06.pais (nome) VALUES ('Austrália');
INSERT INTO mhj06.pais (nome) VALUES ('Áustria');
INSERT INTO mhj06.pais (nome) VALUES ('Azerbaijão');
INSERT INTO mhj06.pais (nome) VALUES ('Baamas');
INSERT INTO mhj06.pais (nome) VALUES ('Bangladeche');
INSERT INTO mhj06.pais (nome) VALUES ('Barbados');
INSERT INTO mhj06.pais (nome) VALUES ('Barém');
INSERT INTO mhj06.pais (nome) VALUES ('Bélgica');
INSERT INTO mhj06.pais (nome) VALUES ('Belize');
INSERT INTO mhj06.pais (nome) VALUES ('Benim');
INSERT INTO mhj06.pais (nome) VALUES ('Bermudas');
INSERT INTO mhj06.pais (nome) VALUES ('Bielorrússia');
INSERT INTO mhj06.pais (nome) VALUES ('Birmânia');
INSERT INTO mhj06.pais (nome) VALUES ('Bolívia');
INSERT INTO mhj06.pais (nome) VALUES ('Bósnia e Herzegovina');
INSERT INTO mhj06.pais (nome) VALUES ('Botsuana');
INSERT INTO mhj06.pais (nome) VALUES ('Brasil');
INSERT INTO mhj06.pais (nome) VALUES ('Brunei');
INSERT INTO mhj06.pais (nome) VALUES ('Bulgária');
INSERT INTO mhj06.pais (nome) VALUES ('Burquina Faso');
INSERT INTO mhj06.pais (nome) VALUES ('Burúndi');
INSERT INTO mhj06.pais (nome) VALUES ('Butão');
INSERT INTO mhj06.pais (nome) VALUES ('Cabo Verde');
INSERT INTO mhj06.pais (nome) VALUES ('Camarões');
INSERT INTO mhj06.pais (nome) VALUES ('Camboja');
INSERT INTO mhj06.pais (nome) VALUES ('Canadá');
INSERT INTO mhj06.pais (nome) VALUES ('Catar');
INSERT INTO mhj06.pais (nome) VALUES ('Cazaquistão');
INSERT INTO mhj06.pais (nome) VALUES ('Chade');
INSERT INTO mhj06.pais (nome) VALUES ('Chile');
INSERT INTO mhj06.pais (nome) VALUES ('China');
INSERT INTO mhj06.pais (nome) VALUES ('Chipre');
INSERT INTO mhj06.pais (nome) VALUES ('Clipperton Island');
INSERT INTO mhj06.pais (nome) VALUES ('Colômbia');
INSERT INTO mhj06.pais (nome) VALUES ('Comores');
INSERT INTO mhj06.pais (nome) VALUES ('Congo-Brazzaville');
INSERT INTO mhj06.pais (nome) VALUES ('Congo-Kinshasa');
INSERT INTO mhj06.pais (nome) VALUES ('Coral Sea Islands');
INSERT INTO mhj06.pais (nome) VALUES ('Coreia do Norte');
INSERT INTO mhj06.pais (nome) VALUES ('Coreia do Sul');
INSERT INTO mhj06.pais (nome) VALUES ('Costa do Marfim');
INSERT INTO mhj06.pais (nome) VALUES ('Costa Rica');
INSERT INTO mhj06.pais (nome) VALUES ('Croácia');
INSERT INTO mhj06.pais (nome) VALUES ('Cuba');
INSERT INTO mhj06.pais (nome) VALUES ('Curacao');
INSERT INTO mhj06.pais (nome) VALUES ('Dhekelia');
INSERT INTO mhj06.pais (nome) VALUES ('Dinamarca');
INSERT INTO mhj06.pais (nome) VALUES ('Domínica');
INSERT INTO mhj06.pais (nome) VALUES ('Egipto');
INSERT INTO mhj06.pais (nome) VALUES ('Emiratos Árabes Unidos');
INSERT INTO mhj06.pais (nome) VALUES ('Equador');
INSERT INTO mhj06.pais (nome) VALUES ('Eritreia');
INSERT INTO mhj06.pais (nome) VALUES ('Eslováquia');
INSERT INTO mhj06.pais (nome) VALUES ('Eslovénia');
INSERT INTO mhj06.pais (nome) VALUES ('Espanha');
INSERT INTO mhj06.pais (nome) VALUES ('Estados Unidos');
INSERT INTO mhj06.pais (nome) VALUES ('Estónia');
INSERT INTO mhj06.pais (nome) VALUES ('Etiópia');
INSERT INTO mhj06.pais (nome) VALUES ('Faroé');
INSERT INTO mhj06.pais (nome) VALUES ('Fiji');
INSERT INTO mhj06.pais (nome) VALUES ('Filipinas');
INSERT INTO mhj06.pais (nome) VALUES ('Finlândia');
INSERT INTO mhj06.pais (nome) VALUES ('França');
INSERT INTO mhj06.pais (nome) VALUES ('Gabão');
INSERT INTO mhj06.pais (nome) VALUES ('Gâmbia');
INSERT INTO mhj06.pais (nome) VALUES ('Gana');
INSERT INTO mhj06.pais (nome) VALUES ('Gaza Strip');
INSERT INTO mhj06.pais (nome) VALUES ('Geórgia');
INSERT INTO mhj06.pais (nome) VALUES ('Geórgia do Sul e Sandwich do Sul');
INSERT INTO mhj06.pais (nome) VALUES ('Gibraltar');
INSERT INTO mhj06.pais (nome) VALUES ('Granada');
INSERT INTO mhj06.pais (nome) VALUES ('Grécia');
INSERT INTO mhj06.pais (nome) VALUES ('Gronelândia');
INSERT INTO mhj06.pais (nome) VALUES ('Guame');
INSERT INTO mhj06.pais (nome) VALUES ('Guatemala');
INSERT INTO mhj06.pais (nome) VALUES ('Guernsey');
INSERT INTO mhj06.pais (nome) VALUES ('Guiana');
INSERT INTO mhj06.pais (nome) VALUES ('Guiné');
INSERT INTO mhj06.pais (nome) VALUES ('Guiné Equatorial');
INSERT INTO mhj06.pais (nome) VALUES ('Guiné-Bissau');
INSERT INTO mhj06.pais (nome) VALUES ('Haiti');
INSERT INTO mhj06.pais (nome) VALUES ('Honduras');
INSERT INTO mhj06.pais (nome) VALUES ('Hong Kong');
INSERT INTO mhj06.pais (nome) VALUES ('Hungria');
INSERT INTO mhj06.pais (nome) VALUES ('Iémen');
INSERT INTO mhj06.pais (nome) VALUES ('Ilha Bouvet');
INSERT INTO mhj06.pais (nome) VALUES ('Ilha do Natal');
INSERT INTO mhj06.pais (nome) VALUES ('Ilha Norfolk');
INSERT INTO mhj06.pais (nome) VALUES ('Ilhas Caimão');
INSERT INTO mhj06.pais (nome) VALUES ('Ilhas Cook');
INSERT INTO mhj06.pais (nome) VALUES ('Ilhas dos Cocos');
INSERT INTO mhj06.pais (nome) VALUES ('Ilhas Falkland');
INSERT INTO mhj06.pais (nome) VALUES ('Ilhas Heard e McDonald');
INSERT INTO mhj06.pais (nome) VALUES ('Ilhas Marshall');
INSERT INTO mhj06.pais (nome) VALUES ('Ilhas Salomão');
INSERT INTO mhj06.pais (nome) VALUES ('Ilhas Turcas e Caicos');
INSERT INTO mhj06.pais (nome) VALUES ('Ilhas Virgens Americanas');
INSERT INTO mhj06.pais (nome) VALUES ('Ilhas Virgens Britânicas');
INSERT INTO mhj06.pais (nome) VALUES ('Índia');
INSERT INTO mhj06.pais (nome) VALUES ('Indian Ocean');
INSERT INTO mhj06.pais (nome) VALUES ('Indonésia');
INSERT INTO mhj06.pais (nome) VALUES ('Irão');
INSERT INTO mhj06.pais (nome) VALUES ('Iraque');
INSERT INTO mhj06.pais (nome) VALUES ('Irlanda');
INSERT INTO mhj06.pais (nome) VALUES ('Islândia');
INSERT INTO mhj06.pais (nome) VALUES ('Israel');
INSERT INTO mhj06.pais (nome) VALUES ('Itália');
INSERT INTO mhj06.pais (nome) VALUES ('Jamaica');
INSERT INTO mhj06.pais (nome) VALUES ('Jan Mayen');
INSERT INTO mhj06.pais (nome) VALUES ('Japão');
INSERT INTO mhj06.pais (nome) VALUES ('Jersey');
INSERT INTO mhj06.pais (nome) VALUES ('Jibuti');
INSERT INTO mhj06.pais (nome) VALUES ('Jordânia');
INSERT INTO mhj06.pais (nome) VALUES ('Kosovo');
INSERT INTO mhj06.pais (nome) VALUES ('Kuwait');
INSERT INTO mhj06.pais (nome) VALUES ('Laos');
INSERT INTO mhj06.pais (nome) VALUES ('Lesoto');
INSERT INTO mhj06.pais (nome) VALUES ('Letónia');
INSERT INTO mhj06.pais (nome) VALUES ('Líbano');
INSERT INTO mhj06.pais (nome) VALUES ('Libéria');
INSERT INTO mhj06.pais (nome) VALUES ('Líbia');
INSERT INTO mhj06.pais (nome) VALUES ('Listenstaine');
INSERT INTO mhj06.pais (nome) VALUES ('Lituânia');
INSERT INTO mhj06.pais (nome) VALUES ('Luxemburgo');
INSERT INTO mhj06.pais (nome) VALUES ('Macau');
INSERT INTO mhj06.pais (nome) VALUES ('Macedónia');
INSERT INTO mhj06.pais (nome) VALUES ('Madagáscar');
INSERT INTO mhj06.pais (nome) VALUES ('Malásia');
INSERT INTO mhj06.pais (nome) VALUES ('Malávi');
INSERT INTO mhj06.pais (nome) VALUES ('Maldivas');
INSERT INTO mhj06.pais (nome) VALUES ('Mali');
INSERT INTO mhj06.pais (nome) VALUES ('Malta');
INSERT INTO mhj06.pais (nome) VALUES ('Man, Isle of');
INSERT INTO mhj06.pais (nome) VALUES ('Marianas do Norte');
INSERT INTO mhj06.pais (nome) VALUES ('Marrocos');
INSERT INTO mhj06.pais (nome) VALUES ('Maurícia');
INSERT INTO mhj06.pais (nome) VALUES ('Mauritânia');
INSERT INTO mhj06.pais (nome) VALUES ('México');
INSERT INTO mhj06.pais (nome) VALUES ('Micronésia');
INSERT INTO mhj06.pais (nome) VALUES ('Moçambique');
INSERT INTO mhj06.pais (nome) VALUES ('Moldávia');
INSERT INTO mhj06.pais (nome) VALUES ('Mónaco');
INSERT INTO mhj06.pais (nome) VALUES ('Mongólia');
INSERT INTO mhj06.pais (nome) VALUES ('Monserrate');
INSERT INTO mhj06.pais (nome) VALUES ('Montenegro');
INSERT INTO mhj06.pais (nome) VALUES ('Mundo');
INSERT INTO mhj06.pais (nome) VALUES ('Namíbia');
INSERT INTO mhj06.pais (nome) VALUES ('Nauru');
INSERT INTO mhj06.pais (nome) VALUES ('Navassa Island');
INSERT INTO mhj06.pais (nome) VALUES ('Nepal');
INSERT INTO mhj06.pais (nome) VALUES ('Nicarágua');
INSERT INTO mhj06.pais (nome) VALUES ('Níger');
INSERT INTO mhj06.pais (nome) VALUES ('Nigéria');
INSERT INTO mhj06.pais (nome) VALUES ('Niue');
INSERT INTO mhj06.pais (nome) VALUES ('Noruega');
INSERT INTO mhj06.pais (nome) VALUES ('Nova Caledónia');
INSERT INTO mhj06.pais (nome) VALUES ('Nova Zelândia');
INSERT INTO mhj06.pais (nome) VALUES ('Omã');
INSERT INTO mhj06.pais (nome) VALUES ('Pacific Ocean');
INSERT INTO mhj06.pais (nome) VALUES ('Países Baixos');
INSERT INTO mhj06.pais (nome) VALUES ('Palau');
INSERT INTO mhj06.pais (nome) VALUES ('Panamá');
INSERT INTO mhj06.pais (nome) VALUES ('Papua-Nova Guiné');
INSERT INTO mhj06.pais (nome) VALUES ('Paquistão');
INSERT INTO mhj06.pais (nome) VALUES ('Paracel Islands');
INSERT INTO mhj06.pais (nome) VALUES ('Paraguai');
INSERT INTO mhj06.pais (nome) VALUES ('Peru');
INSERT INTO mhj06.pais (nome) VALUES ('Pitcairn');
INSERT INTO mhj06.pais (nome) VALUES ('Polinésia Francesa');
INSERT INTO mhj06.pais (nome) VALUES ('Polónia');
INSERT INTO mhj06.pais (nome) VALUES ('Porto Rico');
INSERT INTO mhj06.pais (nome) VALUES ('Portugal');
INSERT INTO mhj06.pais (nome) VALUES ('Quénia');
INSERT INTO mhj06.pais (nome) VALUES ('Quirguizistão');
INSERT INTO mhj06.pais (nome) VALUES ('Quiribáti');
INSERT INTO mhj06.pais (nome) VALUES ('Reino Unido');
INSERT INTO mhj06.pais (nome) VALUES ('República Centro-Africana');
INSERT INTO mhj06.pais (nome) VALUES ('República Dominicana');
INSERT INTO mhj06.pais (nome) VALUES ('Roménia');
INSERT INTO mhj06.pais (nome) VALUES ('Ruanda');
INSERT INTO mhj06.pais (nome) VALUES ('Rússia');
INSERT INTO mhj06.pais (nome) VALUES ('Salvador');
INSERT INTO mhj06.pais (nome) VALUES ('Samoa');
INSERT INTO mhj06.pais (nome) VALUES ('Samoa Americana');
INSERT INTO mhj06.pais (nome) VALUES ('Santa Helena');
INSERT INTO mhj06.pais (nome) VALUES ('Santa Lúcia');
INSERT INTO mhj06.pais (nome) VALUES ('São Bartolomeu');
INSERT INTO mhj06.pais (nome) VALUES ('São Cristóvão e Neves');
INSERT INTO mhj06.pais (nome) VALUES ('São Marinho');
INSERT INTO mhj06.pais (nome) VALUES ('São Martinho');
INSERT INTO mhj06.pais (nome) VALUES ('São Pedro e Miquelon');
INSERT INTO mhj06.pais (nome) VALUES ('São Tomé e Príncipe');
INSERT INTO mhj06.pais (nome) VALUES ('São Vicente e Granadinas');
INSERT INTO mhj06.pais (nome) VALUES ('Sara Ocidental');
INSERT INTO mhj06.pais (nome) VALUES ('Seicheles');
INSERT INTO mhj06.pais (nome) VALUES ('Senegal');
INSERT INTO mhj06.pais (nome) VALUES ('Serra Leoa');
INSERT INTO mhj06.pais (nome) VALUES ('Sérvia');
INSERT INTO mhj06.pais (nome) VALUES ('Singapura');
INSERT INTO mhj06.pais (nome) VALUES ('Sint Maarten');
INSERT INTO mhj06.pais (nome) VALUES ('Síria');
INSERT INTO mhj06.pais (nome) VALUES ('Somália');
INSERT INTO mhj06.pais (nome) VALUES ('Southern Ocean');
INSERT INTO mhj06.pais (nome) VALUES ('Spratly Islands');
INSERT INTO mhj06.pais (nome) VALUES ('Sri Lanca');
INSERT INTO mhj06.pais (nome) VALUES ('Suazilândia');
INSERT INTO mhj06.pais (nome) VALUES ('Sudão');
INSERT INTO mhj06.pais (nome) VALUES ('Sudão do Sul');
INSERT INTO mhj06.pais (nome) VALUES ('Suécia');
INSERT INTO mhj06.pais (nome) VALUES ('Suíça');
INSERT INTO mhj06.pais (nome) VALUES ('Suriname');
INSERT INTO mhj06.pais (nome) VALUES ('Svalbard e Jan Mayen');
INSERT INTO mhj06.pais (nome) VALUES ('Tailândia');
INSERT INTO mhj06.pais (nome) VALUES ('Taiwan');
INSERT INTO mhj06.pais (nome) VALUES ('Tajiquistão');
INSERT INTO mhj06.pais (nome) VALUES ('Tanzânia');
INSERT INTO mhj06.pais (nome) VALUES ('Território Britânico do Oceano Índico');
INSERT INTO mhj06.pais (nome) VALUES ('Territórios Austrais Franceses');
INSERT INTO mhj06.pais (nome) VALUES ('Timor Leste');
INSERT INTO mhj06.pais (nome) VALUES ('Togo');
INSERT INTO mhj06.pais (nome) VALUES ('Tokelau');
INSERT INTO mhj06.pais (nome) VALUES ('Tonga');
INSERT INTO mhj06.pais (nome) VALUES ('Trindade e Tobago');
INSERT INTO mhj06.pais (nome) VALUES ('Tunísia');
INSERT INTO mhj06.pais (nome) VALUES ('Turquemenistão');
INSERT INTO mhj06.pais (nome) VALUES ('Turquia');
INSERT INTO mhj06.pais (nome) VALUES ('Tuvalu');
INSERT INTO mhj06.pais (nome) VALUES ('Ucrânia');
INSERT INTO mhj06.pais (nome) VALUES ('Uganda');
INSERT INTO mhj06.pais (nome) VALUES ('União Europeia');
INSERT INTO mhj06.pais (nome) VALUES ('Uruguai');
INSERT INTO mhj06.pais (nome) VALUES ('Usbequistão');
INSERT INTO mhj06.pais (nome) VALUES ('Vanuatu');
INSERT INTO mhj06.pais (nome) VALUES ('Vaticano');
INSERT INTO mhj06.pais (nome) VALUES ('Venezuela');
INSERT INTO mhj06.pais (nome) VALUES ('Vietname');
INSERT INTO mhj06.pais (nome) VALUES ('Wake Island');
INSERT INTO mhj06.pais (nome) VALUES ('Wallis e Futuna');
INSERT INTO mhj06.pais (nome) VALUES ('West Bank');
INSERT INTO mhj06.pais (nome) VALUES ('Zâmbia');
INSERT INTO mhj06.pais (nome) VALUES ('Zimbabué');