MERGE INTO pais (id, nome) VALUES (1, 'Afeganistão');
MERGE INTO pais (id, nome) VALUES (2, 'África do Sul');
MERGE INTO pais (id, nome) VALUES (3, 'Akrotiri');
MERGE INTO pais (id, nome) VALUES (4, 'Albânia');
MERGE INTO pais (id, nome) VALUES (5, 'Alemanha');
MERGE INTO pais (id, nome) VALUES (6, 'Andorra');
MERGE INTO pais (id, nome) VALUES (7, 'Angola');
MERGE INTO pais (id, nome) VALUES (8, 'Anguila');
MERGE INTO pais (id, nome) VALUES (9, 'Antárctida');
MERGE INTO pais (id, nome) VALUES (10, 'Antígua e Barbuda');
MERGE INTO pais (id, nome) VALUES (11, 'Arábia Saudita');
MERGE INTO pais (id, nome) VALUES (12, 'Arctic Ocean');
MERGE INTO pais (id, nome) VALUES (13, 'Argélia');
MERGE INTO pais (id, nome) VALUES (14, 'Argentina');
MERGE INTO pais (id, nome) VALUES (15, 'Arménia');
MERGE INTO pais (id, nome) VALUES (16, 'Aruba');
MERGE INTO pais (id, nome) VALUES (17, 'Ashmore and Cartier Islands');
MERGE INTO pais (id, nome) VALUES (18, 'Atlantic Ocean');
MERGE INTO pais (id, nome) VALUES (19, 'Austrália');
MERGE INTO pais (id, nome) VALUES (20, 'Áustria');
MERGE INTO pais (id, nome) VALUES (21, 'Azerbaijão');
MERGE INTO pais (id, nome) VALUES (22, 'Baamas');
MERGE INTO pais (id, nome) VALUES (23, 'Bangladeche');
MERGE INTO pais (id, nome) VALUES (24, 'Barbados');
MERGE INTO pais (id, nome) VALUES (25, 'Barém');
MERGE INTO pais (id, nome) VALUES (26, 'Bélgica');
MERGE INTO pais (id, nome) VALUES (27, 'Belize');
MERGE INTO pais (id, nome) VALUES (28, 'Benim');
MERGE INTO pais (id, nome) VALUES (29, 'Bermudas');
MERGE INTO pais (id, nome) VALUES (30, 'Bielorrússia');
MERGE INTO pais (id, nome) VALUES (31, 'Birmânia');
MERGE INTO pais (id, nome) VALUES (32, 'Bolívia');
MERGE INTO pais (id, nome) VALUES (33, 'Bósnia e Herzegovina');
MERGE INTO pais (id, nome) VALUES (34, 'Botsuana');
MERGE INTO pais (id, nome) VALUES (35, 'Brasil');
MERGE INTO pais (id, nome) VALUES (36, 'Brunei');
MERGE INTO pais (id, nome) VALUES (37, 'Bulgária');
MERGE INTO pais (id, nome) VALUES (38, 'Burquina Faso');
MERGE INTO pais (id, nome) VALUES (39, 'Burúndi');
MERGE INTO pais (id, nome) VALUES (40, 'Butão');
MERGE INTO pais (id, nome) VALUES (41, 'Cabo Verde');
MERGE INTO pais (id, nome) VALUES (42, 'Camarões');
MERGE INTO pais (id, nome) VALUES (43, 'Camboja');
MERGE INTO pais (id, nome) VALUES (44, 'Canadá');
MERGE INTO pais (id, nome) VALUES (45, 'Catar');
MERGE INTO pais (id, nome) VALUES (46, 'Cazaquistão');
MERGE INTO pais (id, nome) VALUES (47, 'Chade');
MERGE INTO pais (id, nome) VALUES (48, 'Chile');
MERGE INTO pais (id, nome) VALUES (49, 'China');
MERGE INTO pais (id, nome) VALUES (50, 'Chipre');
MERGE INTO pais (id, nome) VALUES (51, 'Clipperton Island');
MERGE INTO pais (id, nome) VALUES (52, 'Colômbia');
MERGE INTO pais (id, nome) VALUES (53, 'Comores');
MERGE INTO pais (id, nome) VALUES (54, 'Congo-Brazzaville');
MERGE INTO pais (id, nome) VALUES (55, 'Congo-Kinshasa');
MERGE INTO pais (id, nome) VALUES (56, 'Coral Sea Islands');
MERGE INTO pais (id, nome) VALUES (57, 'Coreia do Norte');
MERGE INTO pais (id, nome) VALUES (58, 'Coreia do Sul');
MERGE INTO pais (id, nome) VALUES (59, 'Costa do Marfim');
MERGE INTO pais (id, nome) VALUES (60, 'Costa Rica');
MERGE INTO pais (id, nome) VALUES (61, 'Croácia');
MERGE INTO pais (id, nome) VALUES (62, 'Cuba');
MERGE INTO pais (id, nome) VALUES (63, 'Curacao');
MERGE INTO pais (id, nome) VALUES (64, 'Dhekelia');
MERGE INTO pais (id, nome) VALUES (65, 'Dinamarca');
MERGE INTO pais (id, nome) VALUES (66, 'Domínica');
MERGE INTO pais (id, nome) VALUES (67, 'Egipto');
MERGE INTO pais (id, nome) VALUES (68, 'Emiratos Árabes Unidos');
MERGE INTO pais (id, nome) VALUES (69, 'Equador');
MERGE INTO pais (id, nome) VALUES (70, 'Eritreia');
MERGE INTO pais (id, nome) VALUES (71, 'Eslováquia');
MERGE INTO pais (id, nome) VALUES (72, 'Eslovénia');
MERGE INTO pais (id, nome) VALUES (73, 'Espanha');
MERGE INTO pais (id, nome) VALUES (74, 'Estados Unidos');
MERGE INTO pais (id, nome) VALUES (75, 'Estónia');
MERGE INTO pais (id, nome) VALUES (76, 'Etiópia');
MERGE INTO pais (id, nome) VALUES (77, 'Faroé');
MERGE INTO pais (id, nome) VALUES (78, 'Fiji');
MERGE INTO pais (id, nome) VALUES (79, 'Filipinas');
MERGE INTO pais (id, nome) VALUES (80, 'Finlândia');
MERGE INTO pais (id, nome) VALUES (81, 'França');
MERGE INTO pais (id, nome) VALUES (82, 'Gabão');
MERGE INTO pais (id, nome) VALUES (83, 'Gâmbia');
MERGE INTO pais (id, nome) VALUES (84, 'Gana');
MERGE INTO pais (id, nome) VALUES (85, 'Gaza Strip');
MERGE INTO pais (id, nome) VALUES (86, 'Geórgia');
MERGE INTO pais (id, nome) VALUES (87, 'Geórgia do Sul e Sandwich do Sul');
MERGE INTO pais (id, nome) VALUES (88, 'Gibraltar');
MERGE INTO pais (id, nome) VALUES (89, 'Granada');
MERGE INTO pais (id, nome) VALUES (90, 'Grécia');
MERGE INTO pais (id, nome) VALUES (91, 'Gronelândia');
MERGE INTO pais (id, nome) VALUES (92, 'Guame');
MERGE INTO pais (id, nome) VALUES (93, 'Guatemala');
MERGE INTO pais (id, nome) VALUES (94, 'Guernsey');
MERGE INTO pais (id, nome) VALUES (95, 'Guiana');
MERGE INTO pais (id, nome) VALUES (96, 'Guiné');
MERGE INTO pais (id, nome) VALUES (97, 'Guiné Equatorial');
MERGE INTO pais (id, nome) VALUES (98, 'Guiné-Bissau');
MERGE INTO pais (id, nome) VALUES (99, 'Haiti');
MERGE INTO pais (id, nome) VALUES (100, 'Honduras');
MERGE INTO pais (id, nome) VALUES (101, 'Hong Kong');
MERGE INTO pais (id, nome) VALUES (102, 'Hungria');
MERGE INTO pais (id, nome) VALUES (103, 'Iémen');
MERGE INTO pais (id, nome) VALUES (104, 'Ilha Bouvet');
MERGE INTO pais (id, nome) VALUES (105, 'Ilha do Natal');
MERGE INTO pais (id, nome) VALUES (106, 'Ilha Norfolk');
MERGE INTO pais (id, nome) VALUES (107, 'Ilhas Caimão');
MERGE INTO pais (id, nome) VALUES (108, 'Ilhas Cook');
MERGE INTO pais (id, nome) VALUES (109, 'Ilhas dos Cocos');
MERGE INTO pais (id, nome) VALUES (110, 'Ilhas Falkland');
MERGE INTO pais (id, nome) VALUES (111, 'Ilhas Heard e McDonald');
MERGE INTO pais (id, nome) VALUES (112, 'Ilhas Marshall');
MERGE INTO pais (id, nome) VALUES (113, 'Ilhas Salomão');
MERGE INTO pais (id, nome) VALUES (114, 'Ilhas Turcas e Caicos');
MERGE INTO pais (id, nome) VALUES (115, 'Ilhas Virgens Americanas');
MERGE INTO pais (id, nome) VALUES (116, 'Ilhas Virgens Britânicas');
MERGE INTO pais (id, nome) VALUES (117, 'Índia');
MERGE INTO pais (id, nome) VALUES (118, 'Indian Ocean');
MERGE INTO pais (id, nome) VALUES (119, 'Indonésia');
MERGE INTO pais (id, nome) VALUES (120, 'Irão');
MERGE INTO pais (id, nome) VALUES (121, 'Iraque');
MERGE INTO pais (id, nome) VALUES (122, 'Irlanda');
MERGE INTO pais (id, nome) VALUES (123, 'Islândia');
MERGE INTO pais (id, nome) VALUES (124, 'Israel');
MERGE INTO pais (id, nome) VALUES (125, 'Itália');
MERGE INTO pais (id, nome) VALUES (126, 'Jamaica');
MERGE INTO pais (id, nome) VALUES (127, 'Jan Mayen');
MERGE INTO pais (id, nome) VALUES (128, 'Japão');
MERGE INTO pais (id, nome) VALUES (129, 'Jersey');
MERGE INTO pais (id, nome) VALUES (130, 'Jibuti');
MERGE INTO pais (id, nome) VALUES (131, 'Jordânia');
MERGE INTO pais (id, nome) VALUES (132, 'Kosovo');
MERGE INTO pais (id, nome) VALUES (133, 'Kuwait');
MERGE INTO pais (id, nome) VALUES (134, 'Laos');
MERGE INTO pais (id, nome) VALUES (135, 'Lesoto');
MERGE INTO pais (id, nome) VALUES (136, 'Letónia');
MERGE INTO pais (id, nome) VALUES (137, 'Líbano');
MERGE INTO pais (id, nome) VALUES (138, 'Libéria');
MERGE INTO pais (id, nome) VALUES (139, 'Líbia');
MERGE INTO pais (id, nome) VALUES (140, 'Listenstaine');
MERGE INTO pais (id, nome) VALUES (141, 'Lituânia');
MERGE INTO pais (id, nome) VALUES (142, 'Luxemburgo');
MERGE INTO pais (id, nome) VALUES (143, 'Macau');
MERGE INTO pais (id, nome) VALUES (144, 'Macedónia');
MERGE INTO pais (id, nome) VALUES (145, 'Madagáscar');
MERGE INTO pais (id, nome) VALUES (146, 'Malásia');
MERGE INTO pais (id, nome) VALUES (147, 'Malávi');
MERGE INTO pais (id, nome) VALUES (148, 'Maldivas');
MERGE INTO pais (id, nome) VALUES (149, 'Mali');
MERGE INTO pais (id, nome) VALUES (150, 'Malta');
MERGE INTO pais (id, nome) VALUES (151, 'Man, Isle of');
MERGE INTO pais (id, nome) VALUES (152, 'Marianas do Norte');
MERGE INTO pais (id, nome) VALUES (153, 'Marrocos');
MERGE INTO pais (id, nome) VALUES (154, 'Maurícia');
MERGE INTO pais (id, nome) VALUES (155, 'Mauritânia');
MERGE INTO pais (id, nome) VALUES (156, 'México');
MERGE INTO pais (id, nome) VALUES (157, 'Micronésia');
MERGE INTO pais (id, nome) VALUES (158, 'Moçambique');
MERGE INTO pais (id, nome) VALUES (159, 'Moldávia');
MERGE INTO pais (id, nome) VALUES (160, 'Mónaco');
MERGE INTO pais (id, nome) VALUES (161, 'Mongólia');
MERGE INTO pais (id, nome) VALUES (162, 'Monserrate');
MERGE INTO pais (id, nome) VALUES (163, 'Montenegro');
MERGE INTO pais (id, nome) VALUES (164, 'Mundo');
MERGE INTO pais (id, nome) VALUES (165, 'Namíbia');
MERGE INTO pais (id, nome) VALUES (166, 'Nauru');
MERGE INTO pais (id, nome) VALUES (167, 'Navassa Island');
MERGE INTO pais (id, nome) VALUES (168, 'Nepal');
MERGE INTO pais (id, nome) VALUES (169, 'Nicarágua');
MERGE INTO pais (id, nome) VALUES (170, 'Níger');
MERGE INTO pais (id, nome) VALUES (171, 'Nigéria');
MERGE INTO pais (id, nome) VALUES (172, 'Niue');
MERGE INTO pais (id, nome) VALUES (173, 'Noruega');
MERGE INTO pais (id, nome) VALUES (174, 'Nova Caledónia');
MERGE INTO pais (id, nome) VALUES (175, 'Nova Zelândia');
MERGE INTO pais (id, nome) VALUES (176, 'Omã');
MERGE INTO pais (id, nome) VALUES (177, 'Pacific Ocean');
MERGE INTO pais (id, nome) VALUES (178, 'Países Baixos');
MERGE INTO pais (id, nome) VALUES (179, 'Palau');
MERGE INTO pais (id, nome) VALUES (180, 'Panamá');
MERGE INTO pais (id, nome) VALUES (181, 'Papua-Nova Guiné');
MERGE INTO pais (id, nome) VALUES (182, 'Paquistão');
MERGE INTO pais (id, nome) VALUES (183, 'Paracel Islands');
MERGE INTO pais (id, nome) VALUES (184, 'Paraguai');
MERGE INTO pais (id, nome) VALUES (185, 'Peru');
MERGE INTO pais (id, nome) VALUES (186, 'Pitcairn');
MERGE INTO pais (id, nome) VALUES (187, 'Polinésia Francesa');
MERGE INTO pais (id, nome) VALUES (188, 'Polónia');
MERGE INTO pais (id, nome) VALUES (189, 'Porto Rico');
MERGE INTO pais (id, nome) VALUES (190, 'Portugal');
MERGE INTO pais (id, nome) VALUES (191, 'Quénia');
MERGE INTO pais (id, nome) VALUES (192, 'Quirguizistão');
MERGE INTO pais (id, nome) VALUES (193, 'Quiribáti');
MERGE INTO pais (id, nome) VALUES (194, 'Reino Unido');
MERGE INTO pais (id, nome) VALUES (195, 'República Centro-Africana');
MERGE INTO pais (id, nome) VALUES (196, 'República Dominicana');
MERGE INTO pais (id, nome) VALUES (197, 'Roménia');
MERGE INTO pais (id, nome) VALUES (198, 'Ruanda');
MERGE INTO pais (id, nome) VALUES (199, 'Rússia');
MERGE INTO pais (id, nome) VALUES (200, 'Salvador');
MERGE INTO pais (id, nome) VALUES (201, 'Samoa');
MERGE INTO pais (id, nome) VALUES (202, 'Samoa Americana');
MERGE INTO pais (id, nome) VALUES (203, 'Santa Helena');
MERGE INTO pais (id, nome) VALUES (204, 'Santa Lúcia');
MERGE INTO pais (id, nome) VALUES (205, 'São Bartolomeu');
MERGE INTO pais (id, nome) VALUES (206, 'São Cristóvão e Neves');
MERGE INTO pais (id, nome) VALUES (207, 'São Marinho');
MERGE INTO pais (id, nome) VALUES (208, 'São Martinho');
MERGE INTO pais (id, nome) VALUES (209, 'São Pedro e Miquelon');
MERGE INTO pais (id, nome) VALUES (210, 'São Tomé e Príncipe');
MERGE INTO pais (id, nome) VALUES (211, 'São Vicente e Granadinas');
MERGE INTO pais (id, nome) VALUES (212, 'Sara Ocidental');
MERGE INTO pais (id, nome) VALUES (213, 'Seicheles');
MERGE INTO pais (id, nome) VALUES (214, 'Senegal');
MERGE INTO pais (id, nome) VALUES (215, 'Serra Leoa');
MERGE INTO pais (id, nome) VALUES (216, 'Sérvia');
MERGE INTO pais (id, nome) VALUES (217, 'Singapura');
MERGE INTO pais (id, nome) VALUES (218, 'Sint Maarten');
MERGE INTO pais (id, nome) VALUES (219, 'Síria');
MERGE INTO pais (id, nome) VALUES (220, 'Somália');
MERGE INTO pais (id, nome) VALUES (221, 'Southern Ocean');
MERGE INTO pais (id, nome) VALUES (222, 'Spratly Islands');
MERGE INTO pais (id, nome) VALUES (223, 'Sri Lanca');
MERGE INTO pais (id, nome) VALUES (224, 'Suazilândia');
MERGE INTO pais (id, nome) VALUES (225, 'Sudão');
MERGE INTO pais (id, nome) VALUES (226, 'Sudão do Sul');
MERGE INTO pais (id, nome) VALUES (227, 'Suécia');
MERGE INTO pais (id, nome) VALUES (228, 'Suíça');
MERGE INTO pais (id, nome) VALUES (229, 'Suriname');
MERGE INTO pais (id, nome) VALUES (230, 'Svalbard e Jan Mayen');
MERGE INTO pais (id, nome) VALUES (231, 'Tailândia');
MERGE INTO pais (id, nome) VALUES (232, 'Taiwan');
MERGE INTO pais (id, nome) VALUES (233, 'Tajiquistão');
MERGE INTO pais (id, nome) VALUES (234, 'Tanzânia');
MERGE INTO pais (id, nome) VALUES (235, 'Território Britânico do Oceano Índico');
MERGE INTO pais (id, nome) VALUES (236, 'Territórios Austrais Franceses');
MERGE INTO pais (id, nome) VALUES (237, 'Timor Leste');
MERGE INTO pais (id, nome) VALUES (238, 'Togo');
MERGE INTO pais (id, nome) VALUES (239, 'Tokelau');
MERGE INTO pais (id, nome) VALUES (240, 'Tonga');
MERGE INTO pais (id, nome) VALUES (241, 'Trindade e Tobago');
MERGE INTO pais (id, nome) VALUES (242, 'Tunísia');
MERGE INTO pais (id, nome) VALUES (243, 'Turquemenistão');
MERGE INTO pais (id, nome) VALUES (244, 'Turquia');
MERGE INTO pais (id, nome) VALUES (245, 'Tuvalu');
MERGE INTO pais (id, nome) VALUES (246, 'Ucrânia');
MERGE INTO pais (id, nome) VALUES (247, 'Uganda');
MERGE INTO pais (id, nome) VALUES (248, 'União Europeia');
MERGE INTO pais (id, nome) VALUES (249, 'Uruguai');
MERGE INTO pais (id, nome) VALUES (250, 'Usbequistão');
MERGE INTO pais (id, nome) VALUES (251, 'Vanuatu');
MERGE INTO pais (id, nome) VALUES (252, 'Vaticano');
MERGE INTO pais (id, nome) VALUES (253, 'Venezuela');
MERGE INTO pais (id, nome) VALUES (254, 'Vietname');
MERGE INTO pais (id, nome) VALUES (255, 'Wake Island');
MERGE INTO pais (id, nome) VALUES (256, 'Wallis e Futuna');
MERGE INTO pais (id, nome) VALUES (257, 'West Bank');
MERGE INTO pais (id, nome) VALUES (258, 'Zâmbia');
MERGE INTO pais (id, nome) VALUES (259, 'Zimbabué');

MERGE INTO torneio (id, nome) VALUES (1, 'Mundial de seleções');
MERGE INTO torneio (id, nome) VALUES (2, 'Mundial de clubes');
MERGE INTO torneio (id, nome) VALUES (3, 'Champions Leaugue');
MERGE INTO torneio (id, nome) VALUES (4, 'Copa América');
MERGE INTO torneio (id, nome) VALUES (5, 'Eurocopa');
MERGE INTO torneio (id, nome) VALUES (6, 'Libertadores');
MERGE INTO torneio (id, nome) VALUES (7, 'Sulamericana');
MERGE INTO torneio (id, nome) VALUES (8, 'Copa Confederações');

MERGE INTO grupo (id, nome) VALUES (1, 'A');
MERGE INTO grupo (id, nome) VALUES (2, 'B');
MERGE INTO grupo (id, nome) VALUES (3, 'C');
MERGE INTO grupo (id, nome) VALUES (4, 'D');
MERGE INTO grupo (id, nome) VALUES (5, 'E');
MERGE INTO grupo (id, nome) VALUES (6, 'F');
MERGE INTO grupo (id, nome) VALUES (7, 'G');
MERGE INTO grupo (id, nome) VALUES (8, 'H');

MERGE INTO fase (id, nome) VALUES (1, 'Grupos');
MERGE INTO fase (id, nome) VALUES (2, 'Oitavas');
MERGE INTO fase (id, nome) VALUES (3, 'Quartas');
MERGE INTO fase (id, nome) VALUES (4, 'Semifinal');
MERGE INTO fase (id, nome) VALUES (5, 'Final');
MERGE INTO fase (id, nome) VALUES (6, 'Terceiro Lugar');

MERGE INTO equipe (id, nome, id_pais) VALUES (1, 'Seleção Brasil', 35);
MERGE INTO equipe (id, nome, id_pais) VALUES (2, 'Seleção Espanha', 73);

INSERT INTO jogo (id_equipe_um, id_equipe_dois, placar_equipe_um, placar_equipe_dois, id_fase, id_grupo, id_torneio) VALUES(1,2,3,0,5,null,8);








